# Generated by Django 4.1.6 on 2023-02-10 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الطالب')),
                ('homework', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='درجة الواجبات المسلمة')),
                ('contribution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='درجة المشاركة الفعالة')),
                ('summer', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='درجة الأنشطة الصيفية')),
                ('reserach', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='درجة البحوث')),
                ('attendance', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='درجة الحضور')),
                ('paper_test', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='درجة الاختبار النظري')),
                ('practical_test', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='درجة الاختبار العملي')),
            ],
        ),
    ]
