# Generated by Django 4.1.6 on 2023-02-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_homework_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homework_link',
            field=models.CharField(default='drive.google.com', max_length=1000, verbose_name='رابط البحوث للطالب'),
        ),
    ]
