# Generated by Django 4.1.6 on 2023-02-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_homework_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='research_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='رابط البحوث للطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homework_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='رابط الواجبات المدرسية للطالب'),
        ),
    ]
